apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matching-engine-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: api.matching-engine.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: matching-engine-service
                port:
                  number: 80
